syntax = "proto3";

package servicios;
option go_package = "/serviciosAudio";

service AudioService {
  // Streaming de audio: recibe el nombre del archivo y retorna un flujo de fragmentos
  rpc AudioStream(AudioRequest) returns (stream AudioChunk);
}

message AudioRequest {
  string nombreArchivo = 1; // Ej: "bohemian_rhapsody.mp3", viene del campo Archivo del detalle
}

message AudioChunk {
  bytes data = 1;    // Fragmento de audio
  int32 numero = 2;  // Número de chunk (útil para logs/depuración)
}